# .bash_profile -*- mode: sh -*-

# Use Homebrew bash if available
if [ -x /opt/homebrew/bin/bash ]; then
  export SHELL=/opt/homebrew/bin/bash
fi

# Set PATH
export PATH="$HOME/.local/bin:/opt/homebrew/bin:$PATH"

# Load login settings and environment variables
if [[ -f ~/.profile ]]; then
  source ~/.profile
fi

# Load interactive settings
if [[ -f ~/.bashrc ]]; then
  source ~/.bashrc
fi

export BASH_SILENCE_DEPRECATION_WARNING=1

# Set completion for make targets
complete -W "\`grep -oE '^[a-zA-Z0-9_.-]+:([^=]|$)' ?akefile | sed 's/[^a-zA-Z0-9_.-]*$//'\`" make

# Mise shims
eval "$(mise activate bash)"
